---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://docker.io/envoyproxy/gateway-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  targetNamespace: envoy-gateway-system
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: envoy-gateway
      version: "v1.0.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
  values:
    config:
      envoyGateway:
        gateway:
          controllerName: envoy-gateway